### ISSUE TITLE
Feature request: light version

### ISSUE THREAD

**Issue by oslavq** [Gabriel2392/releases#1]
I'm using this kernel to fix mobile connectivity and few other issues on GSIs (thanks for your work!) and don't need the performance improvements which make my battery drain extremely fast, would it be possible to release a "light" version which contains fixes but not performance improvements?

**Comment by Gabriel2392** [comment]
You can write a KSU/Magisk Module to control the GPU frequencies in /sys/kernel/gpu, like writing 897000 to gpu_max_clock will completely disable the Overclocking. It's the only improvement that increases battery usage.
