### ISSUE TITLE
NfC doesn't work after updating ti 2.3 version

### ISSUE THREAD

**Issue by Lynxiscoool** [Gabriel2392/releases#2]
After updating to version 2.3, NFC disappeared on my Samsung Galxy A33 5g phone. After careful analysis, I came to the conclusion that the application responsible for NFC operation was disabled. Every time the application returns from sleep mode and the phone reboots, it returns to the off mode. If anyone can help, I will be glad!

**Comment by Gabriel2392** [comment]
Reflash your stock odm and vendor_dlkm partitions and use R2.5.
